services:
    character.character_mgr:
        class: ACore\Character\Services\CharacterMgr
        calls:
          - [ setContainer,['@service_container'] ]
          - [ setCharDb, ['@database.doctrine_db'] ]
    character.character_soap_mgr:
        class: ACore\Character\Services\CharacterSoapMgr
        calls:
          - [ setContainer,['@service_container'] ]
          - [ setSoap, ['@soap.soap_mgr'] ]

