soap:
    connections:
        local:
            host: 127.0.0.1,
            port: yourport,
            user: youruser,
            pass:  yourpass,
            protocol: http
        remote:
            host: yourhost,
            port: yourport,
            user: youruser,
            pass:  yourpass,
            protocol: http