services:
    account.account_mgr:
        class: ACore\Account\Services\AccountMgr
        calls:
          - [ setContainer,['@service_container'] ]
          - [ setAuthDb, ['@database.doctrine_db'] ]
    account.account_soap_mgr:
        class: ACore\Account\Services\AccountSoapMgr
        calls:
          - [ setContainer,['@service_container'] ]
          - [ setSoap, ['@soap.soap_mgr'] ]
